# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: cdroot
subtitle:
description: Mostly stuff I find interesting.
keywords: blog,software,cybersecurity,programming
author: Alexandru Petenchea
language: en
timezone: Europe/Bucharest

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://apetenchea.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

port: 4000
server_ip: 0.0.0.0

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:apetenchea/apetenchea.github.io
  branch: master

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

marked:
  gfm: true
  breaks: false
  tables: true

# hexo-tag-github-code
github_code:
  cap: false
  re: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8
  order_by: -date
  
# Category & Tag
default_category:
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD MMM YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus
theme_config:
  projects_url: http://github.com/apetenchea
  direction: ltr
  mathjax:
    enable: true
    per_page: true
    cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/mathjax.js?config=TeX-MML-AM_CHTML
  math:
    enable: true
    per_page: true
    engine: mathjax
  nav:
    home: /
    about: /about/
    articles: /archives/
  social_links:
    github: http://github.com/apetenchea
    linkedin: https://www.linkedin.com/in/alexandru-petenchea-155301143
    mail: mailto:alex.petenchea@gmail.com
  tags_overview: false
  posts_overview:
    show_all_posts: false
    post_count: 8
    sort_updated: false
  archive:
    sort_updated: false
  post:
    show_updated: false
  logo:
    enabled: true
    width: 50
    height: 50
    url: /images/terminal.png
    gravatar: false
  favicon:
    desktop:
      url: /images/favico.png
      gravatar: false
    android:
      url: /images/android-chrome-192x192.png
      gravatar: false
    apple:
      url: /images/apple-touch-icon.png
      gravatar: false
  colorscheme: dark
  page_width: 48
  rss: false

html_minifier:
  enable: true
  exclude:

css_minifier:
  enable: true
  exclude:
    - '*.min.css'

js_minifier:
  enable: true
  mangle: false
  output:
  compress:
  exclude:
    - '*.min.js'
